name: Playwright Tests

on:
  push:
    branches: [main]
    paths: ["servers/front-end-portfolio/**", ".github/workflows/**"]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths: ["servers/front-end-portfolio/**", ".github/workflows/**"]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        working-directory: "./servers/front-end-portfolio"
        run: pnpm playwright install --with-deps

      - name: Run Playwright tests
        working-directory: "./servers/front-end-portfolio"
        run: pnpm playwright test
        env:
          PORTFOLIO_RESUME_URL: ${{secrets.PORTFOLIO_RESUME_URL}}
          NEXT_PUBLIC_LINKEDIN_URL: "https://www.linkedin.com/"
          NEXT_PUBLIC_GITHUB_URL: "https://github.com/"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: "./servers/front-end-portfolio/playwright-report/"
          retention-days: 30
